# PLAY LEVEL VARIABLES
- name: variables from PLAY LEVEL
  hosts: localhost
  vars_files:
    - variables.yaml
  tasks:
  - name: Defining variables
    ansible.builtin.debug:
     msg: "Im learning {{Course}} with {{Trainer}} for the time of {{Duration}}"